version: 0.0
os: linux
files:
  - source: /*
    destination: /home/mysway/cicd.com/djtrump/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/setup_server
      timeout: 300
      runas: mysway
    - location: scripts/restart_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
